### Numpy Library
- Processing N-Dimensional arrays

In [30]:
import numpy as np
li=[1,2,3,'z']
a=np.array(li)
b=np.arange(15)#print list with numbers 0 to 14
c=np.random.randint(1,15,size=10)#1D array
d=np.random.randint(1,15,size=(3,3))#2D array
e=np.random.randint(1,15,size=(3,3,3))#3d array
e.ndim# for which dimension
e.size# for size
e.shape#for shape of e
e.dtype
e.itemsize
print(e)
e[::-1,::-1,::-1]

[[[10  3 12]
  [ 4  6  6]
  [14  3  8]]

 [[ 1  5  5]
  [ 3 14  6]
  [ 2 12 10]]

 [[ 6  5 10]
  [14 10  4]
  [ 5  4  8]]]


array([[[ 8,  4,  5],
        [ 4, 10, 14],
        [10,  5,  6]],

       [[10, 12,  2],
        [ 6, 14,  3],
        [ 5,  5,  1]],

       [[ 8,  3, 14],
        [ 6,  6,  4],
        [12,  3, 10]]])

In [35]:
e.reshape(9,3)

array([[10,  3, 12],
       [ 4,  6,  6],
       [14,  3,  8],
       [ 1,  5,  5],
       [ 3, 14,  6],
       [ 2, 12, 10],
       [ 6,  5, 10],
       [14, 10,  4],
       [ 5,  4,  8]])

In [40]:
import timeit
st=timeit.default_timer()
M=np.ones((3,3))
print("matrix M:\n",M)
print(timeit.default_timer()-st)

matrix M:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0.0009356420005133259


In [39]:
print(M.shape)

(3, 3)
